#' Creates given environments' function dependency (call graph) network.
#' Returns a list of nodes and edges
#'
#' @param envs environment to be graphed, i.e. 'package:utils' or a list of environments
#' @param fun_names function names of which dependencies will be graphed
#'                  (if NULL then all function in environments' are graphed)
createDepnet <- function(envs = .GlobalEnv,
                         fun_names = as.vector(ls.str(.GlobalEnv, mode = 'function'))) {
  depmat <- as.matrix(mvbutils::foodweb(where = envs,
                                        prune = fun_names,
                                        ancestors = TRUE,
                                        descendents = TRUE,
                                        plotting = FALSE)$funmat)

  nodes <- data.frame(id = 1:ncol(depmat), label = colnames(depmat))
  nodes$group <- 'library'
  nodes[nodes$label %in% fun_names, 'group'] <- 'source_code'

  edges <- as.data.frame(which(depmat == 1, arr.ind = TRUE))
  colnames(edges) <- c('from', 'to')

  list(
    nodes = nodes,
    edges = edges
  )
}

createServer <- function(nodes, edges) {
  `%>%` <- magrittr::`%>%`

  server <- function(input, output) {
    output$network <- visNetwork::renderVisNetwork({
      visNetwork::visNetwork(nodes, edges, width = '100%', height = '100%') %>%
        ## visNodes(size = 10) %>%
        visNetwork::visGroups(groupname = 'source_code', color = '#4c4cff') %>%
        visNetwork::visGroups(groupname = 'library', color = '#999999') %>%
        visNetwork::visEdges(arrows = list(to = list(enabled = TRUE))) %>%
        visNetwork::visIgraphLayout(layout = 'layout_in_circle') %>%
        visNetwork::visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE),
                               selectedBy = 'label')
        ## visNetwork::visHierarchicalLayout()
    })
  }

  server
}

#' Creates shiny app of a given network
#'
#' @param network generated by createDepnet
graphDepnetToShiny <- function(network) {
  server <- createServer(network$nodes, network$edges)

  ui <- shiny::fluidPage(
                 visNetwork::visNetworkOutput('network', width = '100vw', height = '100vh')
               )

  app <- shiny::shinyApp(ui = ui, server = server)

  app
}
