#' Example usage of the package.
#' Generates a dependency network from 'utils' package,
#' and starts a shiny web app
#' @export
example <- function() {
  depnet <- createDepnet(envs = c('package:utils'),
                         fun_names = NULL)

  app <- graphDepnetToShiny(depnet)
  shiny::runApp(app, host = '0.0.0.0', port = 8080)
}

#' Creates given environments' function dependency (call graph) network.
#' By default the functions from .GlobalEnv are graphed
#'
#' @param envs environment to be graphed, i.e. 'package:utils' or a list of environments.
#'             Default is .GlobalEnv
#' @param fun_names function names of which dependencies will be graphed
#'                  (if NULL then all function in environments' are graphed).
#'                  Default is functions in .GlobalEnv.
#' @return list containing nodes and edges
#' @export
createDepnet <- function(envs = .GlobalEnv,
                         fun_names = as.vector(ls.str(.GlobalEnv, mode = 'function'))) {
  # so that foodweb -> par doesn't create Rplots.pdf:
  pdf(NULL)

  depmat <- as.matrix(mvbutils::foodweb(where = envs,
                                        prune = fun_names,
                                        ancestors = TRUE,
                                        descendents = TRUE,
                                        plotting = FALSE)$funmat)

  nodes <- data.frame(id = 1:ncol(depmat), label = colnames(depmat))
  nodes$group <- 'library'
  nodes[nodes$label %in% fun_names, 'group'] <- 'source_code'

  edges <- as.data.frame(which(depmat == 1, arr.ind = TRUE))
  colnames(edges) <- c('from', 'to')
  rownames(edges) <- NULL

  list(
    nodes = nodes,
    edges = edges
  )
}

#' @importFrom magrittr %>%
createServer <- function(nodes, edges) {
  server <- function(input, output) {
    output$network <- visNetwork::renderVisNetwork({
      visNetwork::visNetwork(nodes, edges, width = '100%', height = '100%') %>%
        visNetwork::visGroups(groupname = 'source_code', color = '#4c4cff') %>%
        visNetwork::visGroups(groupname = 'library', color = '#999999') %>%
        visNetwork::visEdges(arrows = list(to = list(enabled = TRUE))) %>%
        ## visNetwork::visHierarchicalLayout()
        visNetwork::visIgraphLayout(layout = 'layout_in_circle') %>%
        visNetwork::visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE),
                               selectedBy = 'label')
    })
  }

  server
}

#' Creates shiny app of a given network
#'
#' @param network generated by createDepnet
#' @export
graphDepnetToShiny <- function(network) {
  server <- createServer(network$nodes, network$edges)

  ui <- shiny::fluidPage(
                 visNetwork::visNetworkOutput('network', width = '100vw', height = '100vh')
               )

  app <- shiny::shinyApp(ui = ui, server = server)

  app
}
